alias ac='c;wai;echo;du -h -d 1 ./'
alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
alias aws='ssh -i ~/.ssh/AWSKP.pem ubuntu@nantonizick.com'
alias bb='ssh root@172.16.64.1'
alias c='clear; echo " "; echo "   ________  _____ ______   _______   ________      "; echo "  |\\   __  \\|\\   _ \\  _   \\|\\  ___ \\ |\\   ___  \\    "; echo "  \\ \\  \\|\\  \\ \\  \\\\\\__\\ \\  \\ \\   __/|\\ \\  \\\\ \\  \\   "; echo "   \\ \\  \\\\\\  \\ \\  \\\\|__| \\  \\ \\  \\_|/_\\ \\  \\\\ \\  \\  "; echo "    \\ \\  \\\\\\  \\ \\  \\    \\ \\  \\ \\  \\_|\\ \\ \\  \\\\ \\  \\ "; echo "     \\ \\_______\\ \\__\\    \\ \\__\\ \\_______\\ \\__\\\\ \\__\\"; echo "      \\|_______|\\|__|     \\|__|\\|_______|\\|__| \\|__|"; echo " ";cal; date; echo " "'
alias ca='cat ~/.bash_aliases'
alias demo='ssh nick@192.168.1.31'
alias e='exit'
alias ea='vi ~/.bash_aliases'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'
alias getblob='scp nick@172.20.35.43:/home/nick/Downloads/blob.zip /mnt/d/Videos/temp'
alias getfiles='scp -r nick@172.29.106.161:/home/nick/Downloads/2move/* ./'
alias gh='cd /mnt/c/Users/nick'
alias gmm='youtube-dl -cit --extract-audio --audio-format mp3 '
alias gmml='youtube-dl -cit --extract-audio --audio-format mp3 --batch-file list.txt'
alias grep='grep --color=auto'
alias gtp='cd "/mnt/c/Users/nick/Videos/Home Server/Unsorted/New folder"'
alias gyt='youtube-dl -cit -f mp4 '
alias gytl='youtube-dl -cit -f mp4 --batch-file list.txt'
alias his='vi /home/nick/.bash_history'
alias l='ls -lha'
alias la='ls -A'
alias ll='ls'
alias ls='ls --color=auto'
alias mat='cmatrix -C blue'
alias mint='ssh nick@192.168.1.6'
alias movie='cd /mnt/d/Vaulted/Videos/Movies'
alias pih='ssh nick@192.168.1.20'
alias rtr='ssh root@192.168.1.1'
alias sendfiles='scp -r ./* nick@172.20.35.43:/home/nick/Downloads/2move/'
alias shark='ssh root@172.16.24.1'
alias siem='ssh nick@192.168.1.21'
alias stat='c;cat temp.*;echo " "'
alias tmp='cd /mnt/d/Dynamic/Videos/temp'
alias tv='cd /mnt/d/Vaulted/Videos/TV Shows'
alias upd='sudo apt update'
alias upg='sudo apt upgrade'
alias uyt='sudo -H pip install --upgrade youtube_dl'
alias vm='ssh nick@172.29.106.161'
alias vm2='ssh nick@192.168.1.158'
alias wai='curl ipinfo.io'
alias web='w3m /home/nick/.w3m/bookmark.html'
alias ytl='youtube-dl -cit -f mp4 --batch-file list.txt'
alias ytu='sudo -H pip install --upgrade youtube_dl'
alias dev='ssh -i ~/.ssh/AWSKP.pem ubuntu@dev.antonizick.com'
